[Variables]
;	If this settings file open itself when you load slideshow skin, it means that no image are found
;	Please change Directory variable to your desired folder containing images for slideshow.

;	Image directory
Directory=C:\Users\Finch\Pictures\Wallpapers

;	Size of slideshow skin
SlideWidth=500
SlideHeight=400

;	Whether to include files in sub-directory
SubFolder=1

;	Delay to next picture (in second)
Delay=10

;	!! Heavy performance taxing !!
Animation=0
Duration=3
Repeat=1

;	This variable will update itself automatically when slideshow start
Image_file=C:\Users\Finch\Pictures\Wallpapers\yande.re 392328 ass heels leotard nier_automata qsun_j sword thighhighs yorha_no.2_type_b.jpg
